### ISSUE TITLE
Mark all incomplete topics

### ISSUE THREAD

**Issue by MycroftHolmes1989** [coarse/Modern-Keyboard-PCB-Guide#1]
Please mark the incomplete topics with an "UPCOMING" label. It will really help the readers.

**Comment by spramij** [comment]
The only links in the catalog that work are the first and last ones. My best guess is @coarse hasn't pushed his local updates to the repo.

**Comment by coarse** [comment]
Thanks for the suggestion. spramij is correct, I haven't pushed my local updates yet.

However, I'm looking to rewrite most of it since I will have to relearn keyboard PCB making. I haven't really done it in over a year after all.

I will be including this suggestion to the newer edition of the guide.
